spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinebookstoremanage
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:./uploads/

file:
  upload-dir: ./uploads